defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: dpla_caps_development

test:
  <<: *defaults
  database: dpla_caps_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  database: dpla_caps
  #username: <%= ENV['MONGO_USERNAME'] %>
  #password: <%= ENV['MONGO_PASSWORD'] %>
