require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SitemapsController do

  # This should return the minimal set of attributes required to create a valid
  # Sitemap. As you add validations to Sitemap, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sitemaps as @sitemaps" do
      sitemap = Sitemap.create! valid_attributes
      get :index
      assigns(:sitemaps).should eq([sitemap])
    end
  end

  describe "GET show" do
    it "assigns the requested sitemap as @sitemap" do
      sitemap = Sitemap.create! valid_attributes
      get :show, :id => sitemap.id
      assigns(:sitemap).should eq(sitemap)
    end
  end

  describe "GET new" do
    it "assigns a new sitemap as @sitemap" do
      get :new
      assigns(:sitemap).should be_a_new(Sitemap)
    end
  end

  describe "GET edit" do
    it "assigns the requested sitemap as @sitemap" do
      sitemap = Sitemap.create! valid_attributes
      get :edit, :id => sitemap.id
      assigns(:sitemap).should eq(sitemap)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sitemap" do
        expect {
          post :create, :sitemap => valid_attributes
        }.to change(Sitemap, :count).by(1)
      end

      it "assigns a newly created sitemap as @sitemap" do
        post :create, :sitemap => valid_attributes
        assigns(:sitemap).should be_a(Sitemap)
        assigns(:sitemap).should be_persisted
      end

      it "redirects to the created sitemap" do
        post :create, :sitemap => valid_attributes
        response.should redirect_to(Sitemap.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sitemap as @sitemap" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sitemap.any_instance.stub(:save).and_return(false)
        post :create, :sitemap => {}
        assigns(:sitemap).should be_a_new(Sitemap)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sitemap.any_instance.stub(:save).and_return(false)
        post :create, :sitemap => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sitemap" do
        sitemap = Sitemap.create! valid_attributes
        # Assuming there are no other sitemaps in the database, this
        # specifies that the Sitemap created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sitemap.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sitemap.id, :sitemap => {'these' => 'params'}
      end

      it "assigns the requested sitemap as @sitemap" do
        sitemap = Sitemap.create! valid_attributes
        put :update, :id => sitemap.id, :sitemap => valid_attributes
        assigns(:sitemap).should eq(sitemap)
      end

      it "redirects to the sitemap" do
        sitemap = Sitemap.create! valid_attributes
        put :update, :id => sitemap.id, :sitemap => valid_attributes
        response.should redirect_to(sitemap)
      end
    end

    describe "with invalid params" do
      it "assigns the sitemap as @sitemap" do
        sitemap = Sitemap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sitemap.any_instance.stub(:save).and_return(false)
        put :update, :id => sitemap.id, :sitemap => {}
        assigns(:sitemap).should eq(sitemap)
      end

      it "re-renders the 'edit' template" do
        sitemap = Sitemap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sitemap.any_instance.stub(:save).and_return(false)
        put :update, :id => sitemap.id, :sitemap => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sitemap" do
      sitemap = Sitemap.create! valid_attributes
      expect {
        delete :destroy, :id => sitemap.id
      }.to change(Sitemap, :count).by(-1)
    end

    it "redirects to the sitemaps list" do
      sitemap = Sitemap.create! valid_attributes
      delete :destroy, :id => sitemap.id
      response.should redirect_to(sitemaps_url)
    end
  end

end
